#!/usr/bin/env python3
user_input = input("Please enter an IPv4 IP address:")
## the line below creates a single string that is passed to print()
# print("You told me the IPv4 addres is:" + user_input)
## print() can be given a series of object seperated by a comma
print("You told me the IPv4 address is:", user_input)
vendor_name = input("Please enter the vendor name associated with the device:")
print("The vendor names with that address is:", vendor_name)

